### ISSUE TITLE
Can't remove SEO section from collection

### ISSUE THREAD

**Issue by edalzell** [statamic/seo-pro#102]
How does one remove the SEO section from a collection? I tried `seo: false` in the collection's yaml but the section still showed up.

This is Statamic v2

**Comment by jesseleite** [comment]
This is solved in SEO Pro for v3.

**Comment by jesseleite** [comment]
Going to close this for now.  It's technically not a bug, but a UX improvement we made in v3.  Given that we're not actively improving SEO Pro for v2, I'd just recommend upgrading to v3 at this point.

**Comment by stuartcusackie** [comment]
Does this be re-opened? I am trying: `seo: false` in my collection's YAML but the panel keeps coming back.

On Statamic v3 and SEO Pro 2.3.2
