### ISSUE TITLE
Custom title and descriptions are shown as placeholders

### ISSUE THREAD

**Issue by mikemartin** [statamic/seo-pro#104]
Custom title and descriptions are shown as placeholders but should be editable.

```
seo:
  title: 'The Depression Project: Join our world now!'
  description: 'Understand your depression, get more support, and learn your blueprint to get better!'
```

<img width="830" alt="Screen Shot 2020-08-15 at 9 37 21 am" src="https://user-images.githubusercontent.com/414211/90299856-133a1880-dedb-11ea-946a-92630ba3a4a6.png">

Statamic 3.0.0-beta.44 Pro
Laravel 6.18.26
PHP 7.4.9
SEO Pro 2.05

**Comment by jasonvarga** [comment]
Is the `seo` snippet from an entry?

**Comment by mikemartin** [comment]
@jasonvarga Yes, that's the seo snippet from the homepage content. I also just experienced this when saving the homepage entry.
<img width="773" alt="Screen Shot 2020-08-15 at 10 15 38 am" src="https://user-images.githubusercontent.com/414211/90301008-8db96700-dee0-11ea-9cee-d91d3b73bc33.png">
