### ISSUE TITLE
SEO Pro widget and console errors after running report

### ISSUE THREAD

**Issue by mikemartin** [statamic/seo-pro#105]
After running a SEO Pro report the widget throws this error on the dashboard: https://flareapp.io/share/o7AGpQmp

**Comment by mikemartin** [comment]
Might be related but I'm also getting a 500 error in my console for `/cp/seo-pro/reports`:

<img width="1438" alt="Screen Shot 2020-08-15 at 10 23 12 am" src="https://user-images.githubusercontent.com/414211/90301137-62834780-dee1-11ea-8886-0ba2da814a4a.png">

**Comment by jesseleite** [comment]
Interesting, I guess `->sortDesc()` was added in Laravel 7...  I assume you're on Laravel 6.x?

**Comment by mikemartin** [comment]
@jesseleite Yep. Time to upgrade I guess. :)

```
Statamic 3.0.0-beta.44 Pro
Laravel 6.18.26
PHP 7.4.9
```

**Comment by jesseleite** [comment]
All good, I pushed a fix for 6.x anyway 👍
