### ISSUE TITLE
Adding and saving an image from Site default is deleting description

### ISSUE THREAD

**Issue by sg-modlab** [statamic/seo-pro#107]
When I save an SEO image in site defaults it removes my description in the `content/seo.yaml`file. I believe the reverse happens as well when I save the description the image is removed.

Statamic 3.0.0-beta.44
SEO Pro 2.0.5

**Comment by jesseleite** [comment]
Yes, this one is fixed in https://github.com/statamic/seo-pro/commit/33996db839671a3e2e066c3bcb7bacf13c441ad6.  Will be pushing a hotfix out shortly.

**Comment by jesseleite** [comment]
Fixed in https://github.com/statamic/seo-pro/releases/tag/2.0.6
