### ISSUE TITLE
Saved entry level SEO gets merged over top of disabled section in reports, etc.

### ISSUE THREAD

**Issue by jesseleite** [statamic/seo-pro#109]
On an entry level, `seo` values get wiped when disabled, as it'll save `seo: false` to the entry.  Should disabling SEO on a section should programatically wipe `seo` from every individual entry/term as well?

**Comment by jasonvarga** [comment]
I think yes. It should just remove `seo` from the entry if it exists. It doesn't need to add `seo: false` to each entry.
