### ISSUE TITLE
Add a GUI control and Console command to selectively delete reports 

### ISSUE THREAD

**Issue by pryley** [statamic/seo-pro#117]
From the documentation:

> Reports will stick around until deleted, so you are free to compare reports to see how you are progressing.
> https://github.com/statamic/seo-pro/blob/master/DOCUMENTATION.md#reports

However, it does not mention that in order to delete a report, you must manually delete it from /storages/statamic/seopro/reports/

It would be nice to be able to selectively do this from the Control Panel and `php please`.

Deleting reports also fixed a 500 error that I was experiencing (#116), another reason this might be useful as a `php please` command.

**Comment by jesseleite** [comment]
@pryley Hey sorry for the delay on this one. Just implemented deleting of reports in CP, but curious about your use case for deleting reports via `php please` command?

**Comment by pryley** [comment]
Due to the 500 error I got (see https://github.com/statamic/seo-pro/issues/116) I found it necessary to delete the invalid reports. That was my use case.
