### ISSUE TITLE
SEO data is broken (2.0.9 regression)

### ISSUE THREAD

**Issue by jimblue** [statamic/seo-pro#118]
Just update to 2.0.9 and I'm seing a regression.

All the data from the plugin seems broken.

<img width="427" alt="Screenshot 2020-08-25 at 22 58 34" src="https://user-images.githubusercontent.com/10623367/91227483-e087ef80-e726-11ea-91af-03a3158c89cc.png">
<img width="231" alt="Screenshot 2020-08-25 at 22 58 52" src="https://user-images.githubusercontent.com/10623367/91227486-e1b91c80-e726-11ea-9c1c-13f024ebdfd9.png">

**Comment by jasonvarga** [comment]
You're back! 👋

**Comment by jimblue** [comment]
Sorry lol

**Comment by jesseleite** [comment]
Fixed in 2.0.10.

**Comment by jimblue** [comment]
thanks gentlemen !
