### ISSUE TITLE
Error: Call to a member function absoluteUrl() on null 

### ISSUE THREAD

**Issue by raisonon** [statamic/seo-pro#119]
Error when visiting either:

/cp/collections/articles/entries/create/default
/cp/seo-pro/section-defaults/collections/articles/edit

Error on vendor/statamic/seo-pro/src/Cascade.php:76

Shows on: canonicalUrl() method and this line:

        $url = $this->model->absoluteUrl();

Any suggestions appreciated.

**Comment by jesseleite** [comment]
Hmm, having trouble reproducing this.  Can you provide steps to reproduce from a fresh Statamic install, and maybe the full stack trace via flare share link?

**Comment by raisonon** [comment]
Here is the flare stack trace. I'll try and get around to creating a new laravel site with statamic and seo pro soon if the following stack trace doesn't help: https://flareapp.io/share/A7EEgG7r#F77

**Comment by jesseleite** [comment]
Hey @raisonon, did you get a chance to mess with recreating the issue in a fresh Statamic install?  I still can't reproduce here 🤔

PS. Can you run `php please support:details` and paste the output here?

**Comment by RobertCordes** [comment]
I get this error when I try to create a new collection entry, even when I’m not using the SEO Pro field in the blueprint.

**Comment by jesseleite** [comment]
Weird, I still can't reproduce no matter what I try.  @RobertCordes can you also run `php please support:details` and paste your output?

If either of you can help provide more detailed steps on how to reproduce from a fresh Statamic install, or even upload a public github repo with everything setup to reproduce the issue, that would be greatly appreciated!

**Comment by RobertCordes** [comment]
I have removed the package since then. I only got the error on pages that I've created (or tried to) after installing the package. Already existing pages were working fine. Still these are my details that haven't changed since removing the package:

```
Statamic 3.0.8 Pro
Laravel 7.25.0
PHP 7.4.2
```

One important thing to note might be that I'm working on a multilingual site. It seems like that's causing problems all over the place.

**Comment by raisonon** [comment]
My details:

```
Statamic 3.0.9 Pro
Laravel 7.28.2
PHP 7.4.7
statamic/seo-pro 2.0.12
```

Quite hard to debug in these situation.. Took quite long (45-1hr) to setup new Laravel 7 instance and then jumping through hoops to setup database, fixing migrations, create new admin user, moving over the collections and so forth to try and recreate and debugging all sorts of random error in the process...

Anyway I've managed to recreate the issue with SEO Pro and uploaded a repo here. Appreciate any feedback! Thanks

https://github.com/raisonon/statamic-seo-pro-error

**Comment by jesseleite** [comment]
Lovely, I can reproduce the error with that now. Thank you for taking the time to upload that!

**Comment by jesseleite** [comment]
We found that you were missing a home page.  SEO Pro relies on having at least a root home page at `/`.  Just pushed a more helpful error than `absoluteUrl() on null`.  It'll be in next version, but for now you can set your pages collection to be orderable and create a home page at the top of your structure.  Thanks again for the help on reproducing that one 👍

**Comment by raisonon** [comment]
I have built a home page outside of Statamic as I am using Statamic alongside a Laravel application. How should I go about assigning this with SEO Pro? Thanks

**Comment by damcclean** [comment]
> I have built a home page outside of Statamic as I am using Statamic alongside a Laravel application. How should I go about assigning this with SEO Pro? Thanks

I think that might be a question for another issue.

**Comment by jesseleite** [comment]
@raisonon Mmm yes, good call. Created an issue for that and will address soon, thanks!
