### ISSUE TITLE
Site name position not always working?

### ISSUE THREAD

**Issue by jesseleite** [statamic/seo-pro#122]

**Comment by StefanSchuechl** [comment]
Stopped working for me after the last few releases too. It doesn't show the site name anymore at all.

**Comment by ReneWeCode** [comment]
Same goes for me. I had to do a stupid fix to just be able to show the site name. This issue is probably a quick fix but it's really necessary and crucial.

**Comment by jesseleite** [comment]
Will be fixed in next version 👍
