### ISSUE TITLE
Taxonomy Tag urls in sitemap don't seem right

### ISSUE THREAD

**Issue by sg-modlab** [statamic/seo-pro#124]
So I have a taxonomy for categorizing blog entries. Got an error report from Webmaster tools regarding some links in sitemap.xml getting 404s. Upon review I am seeing `/tag/tag_slug` as the path for these blog tags and they should be `/blog/tag/tag-slug`. The former gets 404, the latter does not.

I appreciate the automagicness of tags makes things a bit tricky. I can say my blog tag is working well on front end. Here are a load of details about what I have setup just in case there is something about my setup (including me) that might be the cause.

Taxonomy Configuration
![image](https://user-images.githubusercontent.com/529067/91922485-22231800-ec9c-11ea-8371-5d14b2446e64.png)

Blueprint Used
![image](https://user-images.githubusercontent.com/529067/91922557-3ff07d00-ec9c-11ea-90e1-0a83f5c1cc96.png)

Template Location
![image](https://user-images.githubusercontent.com/529067/91922442-10417500-ec9c-11ea-836f-b70311484bb9.png)

Content Location
![image](https://user-images.githubusercontent.com/529067/91922534-32d38e00-ec9c-11ea-9c04-486da5fda79f.png)

Code used in blog detail to list out related tags and that has correct url of /blog/tag/tag-slug
```
{{ tag }}
  <li class="mr-2"><a href="{{ url }}" class="font-sans text-xs no-underline text-maroon hover:underline">{{ title }}</a>{{ if ! last }}&nbsp;&nbsp;&#8226;{{ /if }}</li>
{{ /tag }}
```

**Comment by jesseleite** [comment]
Ah yes, good catch.  We'll have to make this a bit smarter, as terms can be routed globally, within a collection, or both ([depending on if the corresponding view(s) exist](https://statamic.dev/taxonomies#routing)) 👍

**Comment by jesseleite** [comment]
Think we got this sorted, tagging release shortly 👍
