### ISSUE TITLE
Can’t include default social image

### ISSUE THREAD

**Issue by fitzage** [statamic/seo-pro#125]
In Statamic V2 with SEO Pro, I could include a custom social image, and then for each collection I could choose a field for collections and use a custom image if I wanted to.

In v3, SEO Pro now only has an option to use a field. This isn’t a huge deal except there’s no way then to have a default image. I’ll have to select an image for every page and entry, even if I want to just use a default image, because there’s no “custom” option anymore.

**Comment by jesseleite** [comment]
@fitzage There is a 'custom' image option, you just have to set your `container` in your `config/statamic/seo-pro.php` file.  (If you don't have that file, run `php artisan vendor:publish --tag="seo-pro-config"`.)

**Comment by fitzage** [comment]
OK, I did that and set up that file like so, but it didn’t seem to change anything. I still can’t select an asset either in the site defaults section or on individual pages:
```
<?php

return [

    'assets' => [
        'container' => 'social',
        'open_graph_preset' => [
            'w' => 1200,
            'h' => 1200,
            'fit' => 'crop',
        ],
    ],

    'sitemap' => [
        'enabled' => true,
        'url' => 'sitemap.xml',
        'expire' => 60,
    ],

    'humans' => [
        'enabled' => true,
        'url' => 'humans.txt',
    ],

];
```

**Comment by fitzage** [comment]
Sorry, that was a cached config issue.

**Comment by jesseleite** [comment]
All good!  I know we're working through other issues on Discord right now, but closing this guy
