### ISSUE TITLE
The field for custom meta description should be a textarea

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/seo-pro#127]
I would highly appreciate a textarea field instead of a small text field for the custom meta description.
The text field is only able to show about 60-70 characters, which makes it really difficult to consider and edit the text.

At the moment, our client needs an external text editor to edit the text. That's not optimal. 

![Skærmbillede 2020-09-09 kl  10 30 38](https://user-images.githubusercontent.com/43215436/92574633-a0c51a00-f287-11ea-8357-c060afe36da8.png)

**Comment by jesseleite** [comment]
Agreed 👍   This'll be in the next SEO Pro update.
