### ISSUE TITLE
humans.txt default view missing variable

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/seo-pro#128]
The view for this is:

```
/* TEAM */

Creator: {{ site_name }}
URL: {{ site_url }}
Description: {{ description }}
...
```

`site_url` doesn't appear to be a variable - `canonical_url` and `home_url` both seem to work.

**Comment by jesseleite** [comment]
Just use `home_url`, that was actually a bug in the old version for v2 as well 😅 .  Updated the default humans.txt view to use `home_url` as well.
