### ISSUE TITLE
Fix for sites without a home entry at `/`

### ISSUE THREAD

**Issue by jesseleite** [statamic/seo-pro#131]
SEO Pro throws errors when a `->model` entry doesn't exist within Cascade. This is because SEO Pro currently requires a home entry at `/`. However, if Statamic is installed into an existing Laravel site with it's own `/` page, SEO Pro should handle null `->model` calls gracefully.

Related to #119.

**Comment by jesseleite** [comment]
@raisonon That should fix your issue, and will be included in next release 👍

**Comment by raisonon** [comment]
Fantastic - thanks for quick work 💪💪
