### ISSUE TITLE
View exception for addon pages in control panel

### ISSUE THREAD

**Issue by addidesign** [statamic/seo-pro#135]
After installing the addon, if navigate to the addon page in the control panel I get a view exception, at the default route - mysite.com/cp/seo-pro

Error - View [index] not found.

**Comment by addidesign** [comment]
Just realised the routes are working fine on my staging site - it's just on my local version they are not?

**Comment by dsturm** [comment]
Hej @addidesign, did you run `php artisan route:clear`?

**Comment by damcclean** [comment]
Someone just had this issue on the Statamic Discord and they resolved it by deleting the `bootstrap/cache/addons.php`, does that fix the problem for your @addidesign.

It's certainly not a long term fix (it'll get regenerated whenever you run any composer commands) so I'd say this is still a bug.

**Comment by jesseleite** [comment]
Need more info to reproduce though.  Is it still happening @addidesign?

**Comment by mnlmaier** [comment]
@damcclean's workaround was solving my issue. for me it's working fine locally, but not working on my staging server... how can we help?

**Comment by addidesign** [comment]
> Need more info to reproduce though. Is it still happening @addidesign?

I think it was down to the connection between my local homestead setup and Statamic. It appears without https locally, non of the routes work. Might be good if this exception is caught somehow within the addon as it's not clear this would be an issue

**Comment by mnlmaier** [comment]
OK guys, it's still regularly happening for me, deleting the `bootstrap/cache/addons.php` does indeed solve the issue consistently. I will post a stack trace here once I can get the error to show up again!

**Comment by jurnskie** [comment]
I'm also experiencing this issue. I can confirm removing the addons.php is a temp fix for me.

**Comment by jasonvarga** [comment]
Are you committing the `bootstrap/cache` directory of your application? Don't do that. It'll get recompiled when you composer install.

**Comment by jurnskie** [comment]
I don' have a server with composer. So i'm installing everything locally and then i upload all the files. But the next time i will ignore the contents of the  boostrap/cache directory.

**Comment by jasonvarga** [comment]
Are you able to run commands at least? If you exclude that directory, you can run the following command after you deploy, and it will generate the appropriate files, as if you were composer installing.

```
php artisan package:discover && php artisan statamic:install
```

**Comment by jasonvarga** [comment]
This will be fixed in the core. See https://github.com/statamic/cms/pull/2761
You'll be able to ignore my last comments and continue to just plop the files on the server like you were originally doing.
