### ISSUE TITLE
Canonical URL field and/or ability to disable query string?

### ISSUE THREAD

**Issue by jesseleite** [statamic/seo-pro#137]
Though people can customize their canonical URL using a view composer, ie)

```php
View::composer('seo-pro::meta', function ($view) {
  $view->with('canonical_url', '/my-better-canonical-url');
});
```

We've had several requests to make the canonical URL customizable as a standard SEO Pro field on entries/terms/sections/etc.

Also some people are fine with the default, but the pagination query string in the canonical URL (ie. https://jesse.uncle/family?page=2) seems to be a controversial thing.  Maybe we could also add a config option to quickly disable the query string on all default canonical URLs.

**Comment by robdekort** [comment]
Personally I'd make it configurable in the SEO tab to support all use cases without having users to add their own fields. Something like this should work:

<img width="798" alt="Screenshot 2020-10-14 at 15 06 46" src="https://user-images.githubusercontent.com/69107412/95993059-ee0c4c80-0e2e-11eb-8429-a3969e4f1e5b.png">
<img width="801" alt="Screenshot 2020-10-14 at 15 06 53" src="https://user-images.githubusercontent.com/69107412/95993074-f06ea680-0e2e-11eb-9756-0b7d86350ebe.png">
<img width="804" alt="Screenshot 2020-10-14 at 15 06 58" src="https://user-images.githubusercontent.com/69107412/95993081-f2386a00-0e2e-11eb-838c-bdc74952a8cc.png">
