### ISSUE TITLE
How to access SEO data individually?

### ISSUE THREAD

**Issue by efoken** [statamic/seo-pro#14]
Generating the metatags is a nice thing, but how can I access the SEO data individually? I have a custom Pinterest share button and want to pass the SEO title, description and image to the Pinterest share URL...

```html
<a href="http://pinterest.com/pin/create/link/?url={{ current_url | urlencode }}&amp;media={{ image }}&amp;description={{ description | urlencode }}">Pin</a>
```

**Comment by adnankussair** [comment]
@jackmcdade @efoken Was this ever answered. Looking to eliminate the need for another global variable for site_name by using the standard SEO pro field. Thanks!

**Comment by jesseleite** [comment]
In current version of SEO Pro, you can:

```
{{ seo_pro:meta_data }}{{ site_name }}{{ /seo_pro:meta_data }}
```

If you want to inspect what's available in the data, you can:

```
{{ seo_pro:dump_meta_data }}
```
