### ISSUE TITLE
Breaks after update to Statamic 3.0.21

### ISSUE THREAD

**Issue by andershagbard** [statamic/seo-pro#140]
This addon breaks after updating Statamic to 3.0.21. I suspect this is duo to https://github.com/statamic/cms/pull/2707

The error is when calling `{{ seo_pro:meta }}`, it throws an exception that view meta, is not found.

**Comment by sheldonkotyk** [comment]
Verified. It also is broken in the CP.

**Comment by jasonvarga** [comment]
Fixing in a sec. Thanks!
