### ISSUE TITLE
using values from two fields for the title tag

### ISSUE THREAD

**Issue by juergengenser** [statamic/seo-pro#149]
Hi,

is it possible to put together the values from multiple fields using the cp? e.g. `{{ client_name }} - {{ title }}` - while it basically works, it always gets prepended by `@seo`

did I get anything wrong here?

best,
Jürgen

**Comment by jesseleite** [comment]
Yep! Just throw that antlers into the `Custom` option...

![image](https://user-images.githubusercontent.com/5187394/101659836-77e22b80-3a14-11eb-9752-9cac49dcd6c3.png)

Which renders...

![image](https://user-images.githubusercontent.com/5187394/101660070-c1cb1180-3a14-11eb-8518-f600b49cb79e.png)

**Comment by juergengenser** [comment]
that's what I've done, but it actually outputs: `<title>@seo:Title - Subtitle - Site Name</title>`

**Comment by jesseleite** [comment]
@juergengenser Using the `Custom` dropdown option? (It should only be inserting `@seo` if you have it set to `Field`, but not `Custom`.)

**Comment by juergengenser** [comment]
works! always had it set to `field` - nevermind!
