### ISSUE TITLE
Override SEO data in SiteHelpers controllers

### ISSUE THREAD

**Issue by efoken** [statamic/seo-pro#15]
I'm currently doing the following in custom controllers:

```php
datastore()->merge([
    'seo' => [
        'title' => htmlspecialchars($entry->name),
        'description' => htmlspecialchars(str_limit($entry->description, 250)),
    ],
]);
```

This works, of course - but not with the cannocial URL, `alternate_locales` and `last_modified` because it gets overriden in your `TagData` class 😄

So, a cleaner way to override the SEO stuff would be nice :-)

**Comment by efoken** [comment]
Ah, I found a way to get the cannonical URL overriden in my SiteHelpers controllers:

```php
datastore()->merge([
    'page_object' => new \Statamic\Routing\Route(request()->url(), datastore()->getAll()),
]);
```

Maybe this is also related to Statamic? The controllers extending `Statamic\Extend\Controller` are not working very well with theme, layout, the cascade and Antlers templates...

Also it's not well documented - there is just a string returned: https://docs.statamic.com/addons/site-helpers#controllers

**Comment by jasonvarga** [comment]
Why are you wanting to override the values?

**Comment by efoken** [comment]
i.e. I have an `EntryController` with ~500k entries coming from DB using Eloquent models – so I obviously have to set the SEO data in controller like my example in the first comment, or am I wrong? 🙂

**Comment by jesseleite** [comment]
@efoken closing this as it's pretty old, and I don't fully understand the use case.  If you're still wanting this with the latest version of SEO Pro in Statamic v3, let us know and we can possibly re-open!
