### ISSUE TITLE
Feature Request: Option to hide Title on Home Page

### ISSUE THREAD

**Issue by sebszocinski** [statamic/seo-pro#16]
I personally think the home page of a website doesn't need to have the title ie `Home` as it's pretty well obvious...

I used to be able to handle this using this kind of code in my default layout:

```
<title>{{ if title != "Home" }}{{yield:title}}{{ title or site_title }}{{/yield:title}} &mdash; {{ /if }} My Rad Website</title>
```

Which would give me this:

`My Rad Website` = nice

instead of 

`Home — My Rad Website` = ugly

Can we add an option to hide the title if its the Home Page?

**Comment by jackmcdade** [comment]
Coming soon to an update near you!
