### ISSUE TITLE
Get the main locale when getting the plural form

### ISSUE THREAD

**Issue by helloDanuk** [statamic/seo-pro#162]
There is an issue with the plural form when using a translation with a 4 character regional code. In this case only singular is used. Even if the language file provides both.

This issue happened in statamic/core as well, as described here statamic/cms@1d15f33

**Comment by jasonvarga** [comment]
Can you show which translations you're talking about?

**Comment by helloDanuk** [comment]
Sure, I am taking about my PR #155 (de and de-CH translations)

**Comment by jesseleite** [comment]
@jasonvarga regarding this and https://github.com/statamic/cms/commit/1d15f33 in core, should we also be handling underscores, like `de_CH`?

**Comment by jesseleite** [comment]
@jasonvarga regarding this and https://github.com/statamic/cms/commit/1d15f33 in core:

- Should we also be handling underscores, like `de_CH`?
- Should we also port that plural form helper to PHP?
    - I'm using `trans_choice()` in SEO Pro here, and see a few occurrences in core as well.

**Comment by helloDanuk** [comment]
Solved in #155
