### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by artemverbo** [statamic/seo-pro#166]
Hi!

I can see the `seo` field in the REST API results for `entries`, but it doesn't seem to be queriable via GraphQL yet? Is that something on your radar (or maybe it's already there, but I've missed it).

Thank you!

**Comment by jasonvarga** [comment]
Consider this a feature request!

**Comment by el-schneider** [comment]
I would be interested too!

**Comment by el-schneider** [comment]
Any news on that?

Because atm you get the following when trying to query a field:

```gql
{
  "errors": [
    {
      "debugMessage": "Expected a value of type \"String\" but received: {\"title\":\"A custom title for the profile page\"}",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
```

**Comment by jasonvarga** [comment]
No news yet sorry. The issue is still open.

**Comment by strebl** [comment]
@jesseleite should it work in the REST API? I see data if I set custom data on a page, but I don't see the inherited fields.

**Comment by jesseleite** [comment]
GraphQL support was just added in #207 and #281 👍
