### ISSUE TITLE
SEO tag slowing down local development

### ISSUE THREAD

**Issue by nckrtl** [statamic/seo-pro#168]
Hi,

I noticed the seo_pro:meta tag is significantly slowing down local development . Check out these screenshots

Without seo_pro:meta tag
<img width="1262" alt="Screenshot 2021-04-08 at 13 57 08" src="https://user-images.githubusercontent.com/18613261/114023502-41f26e00-9873-11eb-9cb2-a44520503be3.png">

With seo_pro:meta tag
<img width="1263" alt="Screenshot 2021-04-08 at 13 57 26" src="https://user-images.githubusercontent.com/18613261/114023513-4454c800-9873-11eb-85e2-0721d64291c3.png">

These timelines are coming from Laravel Debugbar. I'm working on a Mac with Valet @php8.0.3

Are there perhaps some settings I need to adjust or debug options? Alternative could be to not run the tag in development.

Thanks, Nick

**Comment by jesseleite** [comment]
@nckrtl Absolutely! Though it's opinionated for us to make decisions on environments in core. I'd recommend checking the environment yourself like:

```
{{ if config:app:env === 'production' }}
    {{ seo_pro:meta }}
{{ /if }}
```
