### ISSUE TITLE
Entry title/description not being overwritten

### ISSUE THREAD

**Issue by thomasjohnkane** [statamic/seo-pro#172]
I am using {{ seo:meta }} in my header. I have site defaults set for the plugin. When I update data in the entry specific SEO tab, the page still displays the site defaults. Anything obvious I'm missing here?

**Comment by jesseleite** [comment]
Are you using blade components by chance?

**Comment by jesseleite** [comment]
(Also you mention using `{{ seo:meta }}`; It should be `{{ seo_pro:meta }}`.)

**Comment by thomasjohnkane** [comment]
I'm using a blade component, yes. I pull in an antler file from a blade file. And I am using `{{ seo_pro:meta }}` sorry for the mis-type there. I appreciate any feedback you can offer.

**Comment by thomasjohnkane** [comment]
Sorry, didn't see your link initially. I am using Jetstream and have a blade file that uses `<x-guest-layout>` from Jetstream. Then I use a blade component `<x-seo-tags />` to pull in the rendered `{{ seo_pro:meta }}`.

Based on your workaround, I added `:context="$__data"` to the <x-guest-layout> component, as well as the `<x-seo-tags>` component. Unfortunately, it still doesn't override the seo data for a specific entry (uses the site default).

Any other suggestions or pieces I'm missing?

```
Statamic 3.1.5 Pro
Laravel 8.32.1
PHP 7.4.14
edalzell/blade-directives 3.0
statamic/seo-pro 2.2.0
```

**Comment by jasonvarga** [comment]
You have to also add those changes to the PHP component file. This might not be doable in your situation though.

**Comment by thomasjohnkane** [comment]
Do you mean in the `/View/Components/GuestLayout.php` and `/View/Components/SeoTags.php` files? I have added the changes there as well.

**Comment by thomasjohnkane** [comment]
I just went ahead and switched the `<x-seo-tags />` to be a regular old blade in include `@include('components.seo-tags')` which seems to have solved the problem with the cascade for now.
