### ISSUE TITLE
Meta not rendering correctly when using Blade components

### ISSUE THREAD

**Issue by jesseleite** [statamic/seo-pro#173]
Meta won't render correctly when using the new `<x-component>` Blade components in your front end. This is because SEO Pro relies on [template inheritance](https://laravel.com/docs/8.x/blade#layouts-using-template-inheritance) to render meta passed down by the SEO Cascade. As a workaround, you can pass contextual data into your Blade components:

1. In your blade file, pass `$__data` into your component as a prop...

    ```html
    <x-your-layout-component :context="$__data">
        ...
    </x-your-layout-component>
    ```
    
2. In your PHP component file, merge the passed contextual data into your `data()`...

    ```php
    use Illuminate\View\Component;

    class FrontLayout extends Component
    {
        public $context;

        public function __construct($context)
        {
            $this->context = $context;
        }

        public function data()
        {
            return array_merge(parent::data(), $this->context);
        }
        
        // ...
    }
    ```

Maybe we can improve this experience in the future, but for now we would recommend the above method of passing contextual data to your components.

**Comment by Christophvh** [comment]
Nothing is being rendered in our head tag file. Even after adding the above fix. @jesseleite do we need to send the context to the app-layout file in every single view that this is used?

**Comment by MartinVandersteen** [comment]
I'm having issues with this as well, I do pass the $_data variable and when I dd() it, it has the right info inside it. But still, SEO pro behaves very weirdly and returns "Homepage" as a title for all pages, despite setting it up to use the "title" variable for page collections and me being able to see clearly that the "title" variable in $_data is the right one, as well as page.title. What can I do here ?

**Comment by stuartcusackie** [comment]
@MartinVandersteen's answer seems to work but grabbing and augmenting the entry seems to be having quite a large performance impact. On pagespeed insights I can reduce my 'initial server responsive time' by using the data that has already been augmented by the blade view service provider like so:

`{!! tag('seo_pro:meta', [], collect($__data)->merge(['seo' => $page['seo']])->toArray()) !!}`

Seems to work just the same but my page speeds are much better. Beware though, I haven't done much testing.

**Comment by jesseleite** [comment]
You should now be able to se the `@seo_pro('meta')` blade directive in 3.1.0 (see: https://github.com/statamic/seo-pro/pull/195) 👍
