### ISSUE TITLE
Exclude on specific pages

### ISSUE THREAD

**Issue by axlf** [statamic/seo-pro#18]
Hey there,

I'm fairly new to statamic. Perhaps I'm doing this all wrong.

There is a collection for testimonials, which don't intended to be a site on its own.
The SEO Report Generator always says I should have Meta Descriptions for this collection. Is there a way to disable SEO for a collection?

Bye,
— Alexander

**Comment by jackmcdade** [comment]
Yep! Make sure you're on 1.0.1 and then go into SEO Pro > Section Defaults > Testimonials collection and turn that one off.

![image](https://user-images.githubusercontent.com/44739/43651639-eeef8e1a-9710-11e8-9a5c-f7b58c0be4a6.png)

**Comment by axlf** [comment]
Ouch. How could I overlook that ?!?

Thank you!

**Comment by axlf** [comment]
Related question:

is it possible for single pages?

**Comment by jackmcdade** [comment]
Negative, but technically that would be a separate request.

**Comment by kodeine** [comment]
would be good to have it exclude from pages.
