### ISSUE TITLE
Add ability to exclude sites that shouldn't be treated as languages

### ISSUE THREAD

**Issue by adnankussair** [statamic/seo-pro#188]
Current hreflang tags are output as follows:

<img width="487" alt="CleanShot 2021-08-23 at 14 58 51@2x" src="https://user-images.githubusercontent.com/239259/130525240-7b8a77ea-f6fe-47f1-964c-a75e88ebc2f6.png">

Note: zfi is not an alt language, its a multi site in english (hence needs to support both multisite AND localization on the same install). In the case of the screenshot example (ar and en)

See google's docs on the hreflang tag = https://developers.google.com/search/docs/advanced/crawling/localized-versions

We've currently just manually implemented this using our own logic.

**Comment by rrelmy** [comment]
So you have a localized site (en, ar) and a separate site (zfi) which is not related to the english, arabic site?

You expect on the en and ar site to have
- alternate to en (maybe `/en`)
- alternate to ar (maybe `/ar`)

On zfi
- no special alternate

Related to #182 (wrong href)

**Comment by jesseleite** [comment]
The urls are broken (as mentioned in https://github.com/statamic/seo-pro/issues/138), but leaving this open because your multisite example is a good feature request as well 👍

**Comment by jesseleite** [comment]
@adnankussair Tagged 2.3.1 with config to exclude sites from alternate locale meta. For example, in `config/statamic/seo-pro.php`:

```php
'alternate_locales' => [
    'enabled' => true,
    'excluded_sites' => [`zfi`], // Where `zfi` is the handle in your `sites.php` config
],
```

**Comment by adnankussair** [comment]
Thanks @jesseleite
