### ISSUE TITLE
Add Meta Robot field

### ISSUE THREAD

**Issue by axlf** [statamic/seo-pro#19]
It would be great if you could add a simple select fields (or checkboxes) for meta robots. Could easily fit in the SEO Tab.

```
<meta name="robots" content="noindex, nofollow">
```

```
noindex, nofollow
noindex
nofollow
index, follow (default)
```

I had the use case, where I wanted to hide pages from google with the "noindex, nofollow" tag.

**Comment by mariovass** [comment]
Hey is a nice structure taken from SEOmatic in craft. Definitely useful 

``# robots.txt for {{ siteUrl }}

Sitemap: {{ seomatic.helper.sitemapIndexForSiteId() }}
{% switch seomatic.config.environment %}

{% case "live" %}

# live - don't allow web crawlers to index cpresources/ or vendor/

User-agent: *
Disallow: /cpresources/
Disallow: /vendor/
Disallow: /.env

{% case "staging" %}

# staging - disallow all

User-agent: *
Disallow: /

{% case "local" %}

# local - disallow all

User-agent: *
Disallow: /

{% default %}

# default - don't allow web crawlers to index cpresources/ or vendor/

User-agent: *
Disallow: /cpresources/
Disallow: /vendor/
Disallow: /.env

{% endswitch %}

Sitemap: https://flowhub.com/sitemaps/1/sitemap.xml``

**Comment by jesseleite** [comment]
This is in current version 🎉
