### ISSUE TITLE
SEO Pro Open Graph Image field doesn't work with Spaite Responsive Image Add On

### ISSUE THREAD

**Issue by josephrlee** [statamic/seo-pro#199]
I'm trying to set the image field in SEO Pro to render of a responsive image field, here are some sreenshots below of how I've set things up:

![image](https://user-images.githubusercontent.com/1631062/143306689-e701483c-4f99-4e45-b7dc-2d42fd00929b.png)

![image](https://user-images.githubusercontent.com/1631062/143306708-b318742a-aa10-402e-9eea-2df1765a9189.png)
 
Here’s how the Responsive Image addon and SEO Pro renders out in the entry file:
 
![image](https://user-images.githubusercontent.com/1631062/143306754-930281cc-0e3a-48d6-8026-6279ea4175de.png)
 
Is there a way to type in some sort of child field in the SEO Pro Image field to get it to create a social image off the src field instead, like banner_image:src?

**Comment by jackmcdade** [comment]
I think the only way to do what you're trying to do is to overwrite the SEO Pro `meta.antlers.html` view and customize the template yourself. Here's the docs on how to do just that: https://statamic.com/addons/statamic/seo-pro/docs#advanced-configuration
