### ISSUE TITLE
Missing translation options

### ISSUE THREAD

**Issue by Oleafeon** [statamic/seo-pro#201]
I saw that not everything has been translated in the cp for dutch especially in de dropdowns
![image](https://user-images.githubusercontent.com/20043831/152804768-68547f07-10f3-4482-ab8e-0346a9816d15.png)

is there a way to publish the translations files

**Comment by MarlBurroW** [comment]
Is there a way to publish seo-pro translations in `resources/lang` to be able to complete and version my own seo-pro translations ? Obviously I don't want to edit `vendor/statamic/seo-pro/resources/lang` that is not versionned.

**Comment by Oleafeon** [comment]
I just found out that you can find the files when you run php artisan vendor:publish and then look for the right number
