### ISSUE TITLE
T_STRING sitemap.xml

### ISSUE THREAD

**Issue by mauriciodulce** [statamic/seo-pro#22]
Hello, 
I have a problem in my prod env.
1. The menu don't display in the cp, only show the report.
2. I have a error in the sitemap.xml, the page return this alert 
```
Whoops, looks like something went wrong.
2/2
ErrorException in 31e3a2381381a5b5899d9b6bdcf0b778 line 2:
Parse error: syntax error, unexpected 'version' (T_STRING) (View: site/addons/SeoPro/resources/views/sitemap.blade.php)
```
Version statamic: 2.10.2
PHP: 7.2.x
OS: Ubuntu 18.04.

Tks

**Comment by jasonvarga** [comment]
1.0.2 has been released that fixes this.
