### ISSUE TITLE
Blade layout component: $__data context still required.

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/seo-pro#224]
I'm using blade like so:
`@seo_pro('meta')`

And my Meta Site Defaults is set to use 'title' for the META Title.  Yet every page is showing 'Home | Site Name'.

I checked the Section Defaults too and they were set to inherit which produced a value of 'Home'. So now I have set my section defaults to 'from field' = 'title'.

I have re-saved each page to try and update things but nothing is changing.

I'm not sure if this happened recently or has been like this for while.

Thanks.

**Comment by jesseleite** [comment]
Could you paste the output of `php please support:details` so we can see which versions you are using?

Also, what's in the relevant Section Defaults config for the meta title?

**Comment by stuartcusackie** [comment]
Statamic 3.3.17 Pro
Laravel 9.19.0
PHP 8.1.1
aerni/livewire-forms 3.4.0
jonassiewertsen/statamic-live-search 1.5.1
jonassiewertsen/statamic-livewire 2.9.0
rias/statamic-redirect 2.3.6
spatie/statamic-responsive-images dev-main
statamic/seo-pro 3.1.0

Site Defaults
![image](https://user-images.githubusercontent.com/20210934/177295335-0fa578ad-6136-4152-85b9-32cd28d8a61c.png)

Section Defaults (pages collection)
![image](https://user-images.githubusercontent.com/20210934/177295428-69934d32-e3f3-4fbe-ba1f-769b1af76e95.png)

Page Example
![image](https://user-images.githubusercontent.com/20210934/177295613-dbf9a99e-7949-4017-b17d-2fe2e680a6de.png)

Page Example SEO Tab
![image](https://user-images.githubusercontent.com/20210934/177295690-4c674df4-76cd-46ce-a239-364f720fed64.png)

Page Example Output
![image](https://user-images.githubusercontent.com/20210934/177295825-2a50d4e4-89d0-4eac-9676-691ebd39fef9.png)

**Comment by jesseleite** [comment]
Hmm, I wonder why `$__data` would still be required when we literally pass `$__data` through the directive 🤔

https://github.com/statamic/seo-pro/blob/3d0eba3b67bf35d89086db6a9c1da5cad33e2506/src/ServiceProvider.php#L78-L80

**Comment by jesseleite** [comment]
@stuartcusackie Sorry for the bother, but would you mind maybe putting together a test site repo that reproduces the problem? I'm curious what we're doing different from each other.

**Comment by jesseleite** [comment]
> Are you using a blade layout component in your example or template inheritance?

Definitely template inheritance. Maybe that's the issue.

> Happy to send an invite to the actual project if that's okay with you?

If github, feel free to invite jesse @ statamic.

**Comment by jesseleite** [comment]
@stuartcusackie Yeah, it's totally related to the layout component stuff, as you've already discovered [here](https://github.com/statamic/cms/issues/5596#issuecomment-1160732332) and [here](https://github.com/statamic/ideas/issues/822), etc. 

I wouldn't say this is an SEO Pro bug, but rather a feature request to add support for blade layout components. I imagine changes will need to happen in core/cms first.

Anyway, I'll leave this issue open for us to revisit 👍

**Comment by Christophvh** [comment]
Same issue, would love layout component support.

**Comment by isaackearl** [comment]
@jesseleite I have 4 or 5 sites using SEO Pro and blade layout components and I'm in a bind.  Any chance i can hire you to work on resolving this (pay you)?

**Comment by cdmathukiya** [comment]
@Christophvh 
For now the solution is to install this package https://github.com/stuartcusackie/statamic-blade-view-data
and then put this code in you layout component

> @php $context = StatData::context(); @endphp
    @seo_pro('meta', $context)

for me it's working

**Comment by jesseleite** [comment]
Should be fixed in 3.1.1 🤘
