### ISSUE TITLE
Report not being generated on site with thousands of entries

### ISSUE THREAD

**Issue by martink635** [statamic/seo-pro#227]
Hello,
we have an issue that the report is not being generated at all. The website has 2 instances (one with <100 entries in the 2 main collections) and the other with ~1500 entries in 2 collections. On the one with ~1500 entries, the report is never completed (we've left it for a couple of hours). On the smaller instance, the report is generated normally. At first, we were receiving out of memory errors, but as I bumped PHP memory limit to 512 MB, just nothing happens. 

We are running the website on Statamic 3.2.29 and PHP 7.4. 

Not sure how to proceed.

**Comment by joshuablum** [comment]
Hey @martink635,

Would it be possible to give us access to the repo or send us a zipped copy of the site? That way we can try to reproduce it and have a more in-depth look at it.

And what's the output of running `php please support:details`? 
Any more details you can share? Log files etc. would be helpful.

**Comment by martink635** [comment]
Of course we can send everything, what's the best way to go around doing that? There are some sensitive API KEYs, which we are comfortable sharing with you, but not to the general public.

I've updated to Laravel 9 and Statamic 3.3 in a test branch.

1. Output of `php please support:details`:
```
Environment
Application Name: Statamic
Laravel Version: 9.25.1
PHP Version: 8.1.7
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: ses
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: regex
Version: 3.3.30 PRO

Statamic Addons
arckinteractive/statamic-bard-font-size: 1.0.0
aryehraber/statamic-captcha: 1.8.0
cnj/seotamic: 2.0.6
pecotamic/sitemap: 1.4.0
rias/statamic-redirect: 2.4.0
statamic/seo-pro: 3.1.0
```
2. It basically never fails, but never completes… It's stuck in your report is being generated. php usage will go to 100% for a while, then just fall down to a regular value and stays there…
3. It's the same locally

**Comment by martink635** [comment]
This was solved, not sure what happened (several updates did happen, but not sure if this was the issue)

Thanks, closing this.
