### ISSUE TITLE
Custom Canonical URL setting is working on local and staging server but is not working on production site

### ISSUE THREAD

**Issue by JayGeorge** [statamic/seo-pro#229]
I'm having a strange issue where setting a Custom Canonical URL works fine locally and also on staging, but on the production site, it has no effect.

I originally recorded this video for Ryan but he pointed out it's probably better to raise an issue here.

[Here is a 1 minute video](https://drive.google.com/open?id=1Y-j_673IHvK7YeiDflBbtbWipb2cNtDV&authuser=contact%40jaygeorge.co.uk&usp=drive_fs) showing the issue.

Version: 3.3.24 PRO
statamic/seo-pro: 3.1.0
Half measure caching

**Comment by JayGeorge** [comment]
I went through this with Josh Blum and we tried running the following commands:

- php please stache:refresh
- php artisan view:clear

Happy to run through this on a call to show this working on the staging site, but not working on production. I can also share credentials

**Comment by jesseleite** [comment]
Hey @JayGeorge, could you provide the .env file for your production environment (discluding any credentials or sensitive info obviously)?

**Comment by JayGeorge** [comment]
No probs, here are both production and staging sanitized…

[production.txt](https://github.com/statamic/seo-pro/files/9307231/production.txt)
[staging.txt](https://github.com/statamic/seo-pro/files/9307232/staging.txt)

**Comment by jesseleite** [comment]
You mentioned it works locally though. Is it it working in in your 'staging' env there, or are both production and staging broken?

**Comment by JayGeorge** [comment]
It works fine on staging, bizarrely – so from what I can see, it's only when the environment is set to _production_ that doesn't work.

Staging and production are both on the same server, and both share the same repo/commits, etc.

**Comment by jesseleite** [comment]
> I went through this with Josh Blum and we tried running the following commands:
> 
> * php please stache:refresh
> * php artisan view:clear

Does it work on production if you run `php artisan cache:clear` from that app directory on `production`?

...Half measure caching stores statically cached pages in a regular laravel cache, so `stache:refresh` and `view:clear` won't be of help if the problem is half measure related.

**Comment by jesseleite** [comment]
Ah okay, we found the issue...

By default, we preserve pagination query param on canonical urls that are local urls, in line with [this article/study](https://www.searchenginejournal.com/technical-seo/pagination/). It's also mentioned briefly in our [documentation](https://github.com/statamic/seo-pro/blob/master/DOCUMENTATION.md#pagination-meta)...

![CleanShot 2022-08-11 at 11 10 42](https://user-images.githubusercontent.com/5187394/184167035-9e7c098b-6f1f-42c3-8db4-c23899cea4a2.png)

To disable this behaviour, run `php artisan vendor:publish --tag seo-pro-config` and change `enabled_in_canonical_url` to false in config/statamic/seo-pro.php...

```php
'pagination' => [
    'enabled_in_canonical_url' => true,
    'enabled_on_first_page' => false,
],
```

PS. The reason it works as you expect on staging but not production is, your canonical doesn't match your APP_URL on staging, whereas it does on prod.

Let us know how it goes!

**Comment by JayGeorge** [comment]
Thanks for looking into this, Jesse, this fixed my issue
