### ISSUE TITLE
Sitemap should not contain future collection entries

### ISSUE THREAD

**Issue by axlf** [statamic/seo-pro#23]
I'm pretty sure, the sitemap should not contain collection entries which has a date in future.

It's not possible to properly schedule entries when google gets the hint of upcoming entries through the sitemap.

**Comment by jasonvarga** [comment]
It should be configurable.

If you are creating a collection like "events", they will likely have future dates and you would want them to show.

We'll work this out!

**Comment by axlf** [comment]
Yeah. You're right. Events should be in the sitemap.
Blog posts not...

A switch on the collections SEO Pro Tab could do the trick
