### ISSUE TITLE
Removing SEO PRO does not remove SEO pro sections in the Blueprints?

### ISSUE THREAD

**Issue by Sennik** [statamic/seo-pro#237]
After removing SEO PRO after a test I get:

Statamic\Exceptions\FieldtypeNotFoundException
Fieldtype [seo_pro] not found 

When opening collection pages.

I removed SEO pro offically through composer remove

**Comment by duncanmcclean** [comment]
I don't know how much SEO Pro can do about this. 

When you delete some addons, there's bound to be a few references to parts in the addon that's been uninstalled (like in blueprints). 

You can delete these sections manually in the blueprint editor or by editing the blueprint YAML file.

**Comment by Sennik** [comment]
SEO Pro creates these sections in the blue prints so I expect it removes them also when I remove the add-on.

If that is too much of a hassle to program why not explain in the documents how to remove it completely?
