### ISSUE TITLE
No seo meta data with Router::statamic routes

### ISSUE THREAD

**Issue by FrankPeters** [statamic/seo-pro#239]
We are using the [custom Statamic routing method](https://statamic.dev/routing#statamic-routes) to be able to show taxonomies as part of a page content URL. However when using this method the SEO plugin does not seem to know which current Term it's loading and therefore falling back to the homepage meta data.

Is there a way to get this to work?

For reference. `routes/web.php`:
```
Route::statamic('/content-page-slug/{taxonomy_slug}', 'layout-antlers');
```

**Comment by FrankPeters** [comment]
This is really blocking our progress at the moment. Anyone have an idea on how to deal with this?

**Comment by jasonvarga** [comment]
Currently there's not a good way to make it work. In the mean time I'd suggest using a regular route like this:

```php
Route::get('/content-page-slug/{taxonomy_slug}', function ($taxonomySlug) {
    return View::make('layout-antlers')
        ->layout('layout')
        ->cascadeContent(Term::find('topics::'.$taxonomySlug));
});
```

Replace `topics` at the end with the appropriate taxonomy.

**Comment by FrankPeters** [comment]
Thank you, we will have a look to see if this will work and let you know.

**Comment by FrankPeters** [comment]
Thank you very much, that seems to have solved it for now. Hope it will be fixed one day to work with Statamic route helper.
