### ISSUE TITLE
`Value` instance type error when merging non-existent `seo` data

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/seo-pro#245]
Just launch a new website. The reports used to run fine on my localhost but now they don't seem to go anywhere:
![image](https://user-images.githubusercontent.com/20210934/207304292-270d55ad-11fd-4b2d-9103-a6536c7e6329.png)

I have tried this on a 'sync' queue and on a 'redis' queue. Yesterday it got to about 4 hours with 0% progress.

**Comment by joshuablum** [comment]
Hey @stuartcusackie,

What's the output of `php please support:details`?

> fine on my localhost but now they don't seem to go anywhere

Like it still works locally but not in production? Or not working locally anymore?

> Just launch[ed] a new website.

What did you do prior to when it stopped working? Could you track that in your Git history? Update dependencies? Something else?

Could you please run `php artisan optimize:clear && php please stache:refresh`

Anything in the logs, like `storage/logs/laravel.log`?

**Comment by stuartcusackie** [comment]
Hi, thanks for looking into this so quickly. I have just checked the logs and there seems to be a problem with the default queue jobs:
Illuminate\Foundation\Console\QueuedCommand has been attempted too many times or run too long

I have deleted the queue and started it again but the same problem occurs. I'm pretty sure they only job running on this queue is for SEO Pro reports. I have another queue that works fine.

Environment
Laravel Version: 9.43.0
PHP Version: 8.1.12
Composer Version: 2.2.3
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Statamic
Addons: 7
Antlers: regex
Version: 3.3.60 PRO

Statamic Addons
jonassiewertsen/statamic-live-search: 1.5.1
jonassiewertsen/statamic-livewire: 2.9.0
justbetter/statamic-image-optimize: 1.1.4
rias/statamic-redirect: 2.5.0
spatie/statamic-responsive-images: 2.14.4
statamic/seo-pro: 3.1.2
stuartcusackie/statamic-cache-requester: 1.0.2

**Comment by stuartcusackie** [comment]
I have found more clues after increasing the queue timeout. New errors are appearing:

```
{
    "class": "Error",
    "message": "Call to a member function withPages() on null",
    "code": 0,
    "file": "/home/forge/westwood.ie/vendor/statamic/seo-pro/src/Http/Controllers/ReportController.php:34",
    "trace": [
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54",
```

By the way, having to increase the queue timeout seems like bad practice. Maybe these large jobs should be split into smaller jobs?

**Comment by stuartcusackie** [comment]
New errors appearing now:

```
{
    "class": "TypeError",
    "message": "ArrayIterator::__construct(): Argument #1 ($array) must be of type array, null given",
    "code": 0,
    "file": "/home/forge/westwood.ie/vendor/statamic/cms/src/Fields/Value.php:73",
    "trace": [
        "/home/forge/westwood.ie/vendor/statamic/cms/src/Fields/Value.php:73",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:961",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:808",
        "/home/forge/westwood.ie/vendor/statamic/seo-pro/src/Cascade.php:39",
        "/home/forge/westwood.ie/vendor/statamic/seo-pro/src/Reporting/Report.php:125",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:560",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:739",
        "/home/forge/westwood.ie/vendor/statamic/seo-pro/src/Reporting/Report.php:133",
        "/home/forge/westwood.ie/vendor/statamic/seo-pro/src/Reporting/Report.php:111",
        "/home/forge/westwood.ie/vendor/statamic/seo-pro/src/Reporting/Report.php:106",
        "/home/forge/westwood.ie/vendor/statamic/seo-pro/src/Reporting/Report.php:74",
        "/home/forge/westwood.ie/vendor/statamic/seo-pro/src/Commands/GenerateReportCommand.php:38",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Container/Util.php:41",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Container/Container.php:651",
        "/home/forge/westwood.ie/vendor/laravel/framework/src/Illuminate/Console/Command.php:182",
```

**Comment by jesseleite** [comment]
@stuartcusackie I'm going to say the queue stuff isn't a bug, since we recommend moving to proper queues for larger reports, and link to Laravel docs, etc. in SEO Pro's documentation.

That said, we fixed the error you mentioned in https://github.com/statamic/seo-pro/issues/245#issuecomment-1348367004 and tagged 3.1.3 👍

**Comment by stuartcusackie** [comment]
Thanks, no errors appearing now after upgrading to 3.1.3. Full report generate successfully!

**Comment by jesseleite** [comment]
Maybe this is a good feature request, feel free to open an issue for this. Can't comment on splitting the report job into smaller jobs (that would likely require a bigger overhaul), but we could probably at least add config to allow for running on a non-default queue.
