### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by justkidding96** [statamic/seo-pro#249]
Hi I've facing a problem with the translation see screenshot below. What can I do to fix this issue?

<img width="366" alt="Scherm­afbeelding 2022-12-23 om 10 08 30" src="https://user-images.githubusercontent.com/1297850/209307221-525294f0-94fc-4e38-b749-5150f316e8c7.png">

**Comment by j-jalving** [comment]
I have the same issue. Any word on this?

**Comment by jesseleite** [comment]
@justkidding96 @j-jalving Can we see what you both have configured for your `fallback_locale` in [config/app.php here](https://github.com/statamic/statamic/blob/782ec8850b073710aadf464a290dca6ab839f21f/config/app.php#L99)?

**Comment by jesseleite** [comment]
@justkidding96 @j-jalving Can we see what you both have configured for your `locale` and `fallback_locale` in [config/app.php here](https://github.com/statamic/statamic/blob/782ec8850b073710aadf464a290dca6ab839f21f/config/app.php#L75-L99)?

**Comment by j-jalving** [comment]
Both are set to `nl`. But the problem is simply that the dutch translation files aren't complete.

**Comment by jasonvarga** [comment]
That makes sense then. If `fallback_locale` was `en`, you'd at least see English words rather than the translation keys.

In that case we'd accept a PR to fill out the missing translations. We don't speak Dutch so we rely on third party translation contributions.

Thanks!

**Comment by j-jalving** [comment]
#284

**Comment by j-jalving** [comment]
Does it even look at the fallback_locale option? Found out this weird issue when my CP language is set to Dutch and my `locale` is also set to `nl` and my `fallback_locale` to `en`:

**Overview page**
This one falls back to english like it should:

<img width="958" alt="Screenshot 2023-07-10 at 18 58 43" src="https://github.com/statamic/seo-pro/assets/60800079/a7646c1e-2e8d-4a7e-bb44-8491e9096458">


** Scan page**
This one falls back does not fall back (the english strings seem to be present in the translation file though) :

<img width="685" alt="Screenshot 2023-07-10 at 18 58 31" src="https://github.com/statamic/seo-pro/assets/60800079/b4d57074-3a25-40db-bab7-939118c9b347">

Also, when can we expect the new nl translations to be published to Packagist?

**Comment by jasonvarga** [comment]
Tagged now. Excuse the delay.
