### ISSUE TITLE
Generate report job takes too long

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/seo-pro#262]
My reports won't complete on a site with 400 entries. I am using the Redis queue with Horizon at the default of 60 second timeouts:

![image](https://user-images.githubusercontent.com/20210934/216586288-75d9fd7e-94fe-45d4-92f0-6ff002748c14.png)

I think ideally these jobs should be split (one entry per job). A job that takes 10 minutes to run seems like a bad idea, and this site isn't really that big compared to some.

If that's not happening then a simpler improvement would be a customisable queue in the config. At the moment the only option is to massively increase the timeout of all jobs on the default queue, which I don't like doing.

Thanks!

**Comment by rubzie** [comment]
We're experiencing comparable issues, hope it can be addressed! 🙏🏼

**Comment by jesseleite** [comment]
Just FYI, some pretty big performance improvements coming soon in https://github.com/statamic/seo-pro/pull/304 and https://github.com/statamic/seo-pro/pull/307

**Comment by jesseleite** [comment]
@stuartcusackie @rubzie, some pretty big performance improvements coming in the next release https://github.com/statamic/seo-pro/pull/304 and https://github.com/statamic/seo-pro/pull/307, with more improvements yet to come...

> My reports won't complete on a site with 400 entries

For example, I'm now generating a report for 1000 entries, without a queue even set up, in ~8.5 seconds...

![CleanShot 2023-12-12 at 16 35 33](https://github.com/statamic/seo-pro/assets/5187394/50939557-2717-4a43-ade7-56fb6547c3cf)

**Comment by rubzie** [comment]
> @stuartcusackie @rubzie, some pretty big performance improvements coming in the next release #304 and #307, with more improvements yet to come...

Wooohoo nice, looking forward to it, thanks a lot @jesseleite! Then onto the next challenge, making SEO Pro work for multi site ;)

**Comment by jesseleite** [comment]
Will close this when we tag next version, but see https://github.com/statamic/seo-pro/pull/310 🏎️

**Comment by jesseleite** [comment]
Tagged 5.4.0 🤘
