### ISSUE TITLE
Target class [ReportController] does not exist.

### ISSUE THREAD

**Issue by JonKaric** [statamic/seo-pro#269]
Getting `Target class [ReportController] does not exist.` on the following routes:
- `/site-defaults`
- `/reports`

```

Illuminate\Contracts\Container\BindingResolutionException
Target class [ReportController] does not exist.

Illuminate\Container\Container::build
vendor/laravel/framework/src/Illuminate/Container/Container.php:891

```

<details><summary>Env details</summary>
<p>

Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.0.28
Composer Version: 2.1.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0 Solo

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.0.2
netoka/statamic-inline-assets: 1.0.0
statamic/seo-pro: 5.0.0

</p>
</details>

**Comment by jesseleite** [comment]
The fix for this will be tagged shortly! Thanks 👍
