### ISSUE TITLE
Target class [SiteDefaultsController] does not exist.

### ISSUE THREAD

**Issue by superfantastic** [statamic/seo-pro#270]
Getting `Target class [SiteDefaultsController] does not exist.` on the following route:

`/cp/seo-pro/site-defaults/edit`

Getting a similar response when trying to access reports too.

- PHP 8.1.10
- Statamic 4.0.0
- Laravel 9.52.7
- SEO Pro 5.0.0

**Comment by jesseleite** [comment]
The fix for this will be tagged shortly! Thanks 👍
