### ISSUE TITLE
Site do not redirect to 404 page.

### ISSUE THREAD

**Issue by bispldeveloper** [statamic/seo-pro#279]
Hi. 
While using the seo_pro addon, if I try to add the wrong slug in the URL it displays the below error on the page instead of redirecting to 404 page. Could you please fix it.

BadMethodCallException
Call to undefined method Statamic\Globals\Variables::augmentable()

**Comment by bispldeveloper** [comment]
Our Client is not ready to share repository . The site https://www.eyeweb.co.uk/ is having the problem. Here suppose if we type https://www.eyeweb.co.uk/about-us1 instead of https://www.eyeweb.co.uk/about-us it gives 500 server error. We are expecting it to redirect to 404 page.

**Comment by jasonvarga** [comment]
Please share the error. You can find it in your log file.

**Comment by bispldeveloper** [comment]
> Please share the error. You can find it in your log file.

 
[2023-06-20 13:57:31] production.ERROR: Call to undefined method Statamic\Globals\Variables::augmentable() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Statamic\\Globals\\Variables::augmentable() at /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Data/HasAugmentedInstance.php:109)
[stacktrace]
#0 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Support/Optional.php(128): Statamic\\Globals\\Variables->__call()
#1 /home/forge/www.AwairGB.co.uk/vendor/statamic/seo-pro/src/Tags/SeoProTags.php(39): Illuminate\\Support\\Optional->__call()
#2 /home/forge/www.AwairGB.co.uk/vendor/statamic/seo-pro/src/Tags/SeoProTags.php(29): Statamic\\SeoPro\\Tags\\SeoProTags->metaData()
#3 [internal function]: Statamic\\SeoPro\\Tags\\SeoProTags->meta()
#4 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/View/Antlers/Engine.php(161): call_user_func()
#5 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag()
#6 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/View/Antlers/Parser.php(587): call_user_func_array()
#7 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/View/Antlers/Parser.php(180): Statamic\\View\\Antlers\\Parser->parseCallbackTags()
#8 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/View/Antlers/Parser.php(135): Statamic\\View\\Antlers\\Parser->parse()
#9 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Parser->parseView()
#10 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/View/View.php(195): Statamic\\View\\Antlers\\Engine->get()
#11 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#12 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#13 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/View/View.php(111): Illuminate\\View\\View->render()
#14 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Exceptions/NotFoundHttpException.php(32): Statamic\\View\\View->render()
#15 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Exceptions/NotFoundHttpException.php(19): Statamic\\Exceptions\\NotFoundHttpException->contents()
#16 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(359): Statamic\\Exceptions\\NotFoundHttpException->render()
#17 /home/forge/www.AwairGB.co.uk/app/Exceptions/Handler.php(53): Illuminate\\Foundation\\Exceptions\\Handler->render()
#18 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): App\\Exceptions\\Handler->render()
#19 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(143): Illuminate\\Routing\\Pipeline->handleException()
#20 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\StaticCaching\\Middleware\\Cache->handle()
#22 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AuthGuard->handle()
#24 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AddViewPaths->handle()
#26 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Http/Middleware/Localize.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\Localize->handle()
#28 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\HandleToken->handle()
#30 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StacheLock->handle()
#32 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#34 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#36 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#38 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#40 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#41 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#43 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#45 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#47 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#48 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#49 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#50 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#51 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#52 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle()
#54 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#56 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#58 /home/forge/www.AwairGB.co.uk/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#60 /home/forge/www.AwairGB.co.uk/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#62 /home/forge/www.AwairGB.co.uk/vendor/spatie/laravel-cookie-consent/src/CookieConsentMiddleware.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Spatie\\CookieConsent\\CookieConsentMiddleware->handle()
#64 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#66 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#67 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#69 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#70 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#72 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#74 /home/forge/www.AwairGB.co.uk/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#76 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#78 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#80 /home/forge/www.AwairGB.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#81 /home/forge/www.AwairGB.co.uk/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#82 {main}
"}

**Comment by jesseleite** [comment]
@bispldeveloper What version of SEO Pro are you running? You should be able to find the exact installed version by running `composer info | grep 'seo-pro'`, thanks!

**Comment by bispldeveloper** [comment]
> 

Current seo-pro version is 5.2.0

**Comment by jasonvarga** [comment]
Hi @bispldeveloper we figured out this is probably because you have a global set named `seo`.

Would you be able to rename it? Maybe something like `seo_settings`.

SEO Pro is expecting its own field to be `seo`. There will likely be a number of places this could conflict if you have your own field or global named `seo`.

**Comment by bispldeveloper** [comment]
> Hi @bispldeveloper we figured out this is probably because you have a global set named `seo`.
> 
> Would you be able to rename it? Maybe something like `seo_settings`.
> 
> SEO Pro is expecting its own field to be `seo`. There will likely be a number of places this could conflict if you have your own field or global named `seo`.

Thank you @jasonvarga . Finally it worked :)
