### ISSUE TITLE
It will not generate <meta> tag if Robots field left blank

### ISSUE THREAD

**Issue by bispldeveloper** [statamic/seo-pro#280]
Hi,
It generates meta tag in the header of the site only if I select Robots field with options noindex or noselect.
If we left the field blank, it need to generate the meta tag with value index as shown below
<meta name="robots" content="index" />
Could you please update the addon.

**Comment by jasonvarga** [comment]
The default behavior is to index. You don't need to add a meta tag unless you plan to customize it.

See https://moz.com/learn/seo/robots-meta-directives

> Indexation-controlling parameters:
>
> Index: Tells a search engine to index a page. Note that you don’t need to add this meta tag; it’s the default.
