### ISSUE TITLE
Error in Documentation or Bug with Antlers Code as Description

### ISSUE THREAD

**Issue by sewid** [statamic/seo-pro#287]
In the seo pro docs, there is an example for antlers templating:

```
{{ content | strip_tags | truncate:250:... }}
```

If I use this example code or if I use the code below as description content:

```
{{ content | strip_tags | truncate(150, '...') }}
```

I get this error message:

```
strip_tags(): Argument #1 ($string) must be of type string, array given
```

Statamic Version is: 4.10.2
SEO Pro Version is: 5.2.1

**Comment by jackmcdade** [comment]
This would work if your `content` is a string, but my guess is you're using Bard, which stores its data in an array. In order to truncate Bard text you'd need to loop the tag, get the first text var, and truncate that.

**Comment by sewid** [comment]
Hi @jackmcdade , no, it's a markdown field. If I place

```

{{ content | strip_tags | truncate(150, '...') }}
```

in a template somewhere, it works without problems.

**Comment by jackmcdade** [comment]
Which Antlers parser are you using? You can check in `config/statamic/antlers.php` – you should be using `runtime`.

**Comment by sewid** [comment]
it is `runtime`

**Comment by jackmcdade** [comment]
Okay, I'm gonna have @jesseleite take a look at this, he's the SEO Pro guy and it's clear that something else is at play here 🤔

**Comment by sewid** [comment]
ok, thanks! 😄

**Comment by jesseleite** [comment]
Hey @sewid, I'm having reproducing this with a markdown field 🤔 Could you maybe provide a simple example site repo with the issue reproduced that we could pull down by chance?

**Comment by sewid** [comment]
Hey @jesseleite, I've sent you an email about two weeks ago where you can find the code. Have you seen it?

**Comment by jesseleite** [comment]
I feel like we might have spoken back in 2023 by email, but I'm having trouble tracking it down now. Going to close this for now, but if this is still an issue for you, please re-open and we'll absolutely take a look! ❤️
