### ISSUE TITLE
Add missing markup to fix Google Search Console Error

### ISSUE THREAD

**Issue by jimblue** [statamic/seo-pro#290]
As documented on [www.sitemaps.org](https://www.sitemaps.org/protocol.html), sitemaps XML format should respect the following markup:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url></url>
<url></url>
<url></url>
...
```

But sitemap generated by **Seo-Pro** extension looks like this:

```xml
<urlset>
<url></url>
<url></url>
<url></url>
...
```

 And because of this missing markup Google Search Console returns the following error:

![Screenshot 2023-09-13 at 00 58 03](https://github.com/statamic/seo-pro/assets/10623367/4bf8f499-cf21-4bb9-ad56-686e6f781985)

**Comment by jasonvarga** [comment]
Have you customized the template? Ours has both xml header and xmlns attribute on the urlset tag.

https://github.com/statamic/seo-pro/blob/master/resources/views/generated/sitemap.antlers.html

**Comment by jimblue** [comment]
Thank you for the hint, I found that the problem is due to my own setup by a HTML compress middleware.
Sorry for noise 😅

**Comment by jasonvarga** [comment]
Ah, good to know!
