### ISSUE TITLE
Support for variables in Site Name field

### ISSUE THREAD

**Issue by peimn** [statamic/seo-pro#30]
<img width="356" alt="screen shot 2018-09-10 at 11 09 13 pm" src="https://user-images.githubusercontent.com/5695187/45317949-ba281400-b550-11e8-8aca-ba3bb3865c09.png">

By now anything we add to this field will be shown for all locales. But we need different site names for each locale. The problem will be solved If we can use localizable global variables like `{{site_name}}`.

**Comment by kodeine** [comment]
i tried this and didnt work, i wondered why =) it would be good to have this feature.

**Comment by jesseleite** [comment]
You can now do this in 2.0.12 👍
