### ISSUE TITLE
 Error ·Closure (Chunk.php:51)

### ISSUE THREAD

**Issue by davideprevosto** [statamic/seo-pro#312]
## Statamic
version 4.42.1

## SEO Pro
version 5.4.0

Trying to creating a report (/seo-pro/reports/1) I am getting the following error:

```
Error Closure (Chunk.php:51)
Call to a member function save() on null
```

The UI is blocked:

<img width="983" alt="image" src="https://github.com/statamic/seo-pro/assets/28837345/bd013175-7398-42bd-9691-2f2a342d3716">

The error stack here:

[error_stack.txt](https://github.com/statamic/seo-pro/files/13839807/error_stack.txt)

Thank you

**Comment by jesseleite** [comment]
@davideprevosto Did it just happen once, or does it happen every time you try to generate a new fresh report?

**Comment by jesseleite** [comment]
Nevermind, found the issue. Thanks for reporting!
