### ISSUE TITLE
Multisite Sitemap Support in SEO Pro

### ISSUE THREAD

**Issue by tf-digital** [statamic/seo-pro#315]
Hello everyone,

I am reaching out to inquire about a specific functionality in the SEO Pro addon for Statamic. My current project involves a multisite setup, and for optimal SEO performance, it is crucial that each site (be it a TLD or a subdomain) has its own separate sitemap. 

Does SEO Pro support the generation of individual sitemaps for each site in a multisite configuration? If so, can somebody explain me how to configure SEO Pro to achieve this?

Understanding the importance of separate sitemaps for each domain in enhancing SEO, this feature would be incredibly beneficial for projects with a multisite architecture.

Thx Steffen

**Comment by duncanmcclean** [comment]
Hey 👋

I don't believe SEO Pro supports generating sitemaps for each of your sites. There's a few existing issues about the topic here:

* #56
* #208

Since there's other issues on this topic, I'm going to close this in favour of them. Feel free to subscribe to those issues for any updates. Thanks!
