### ISSUE TITLE
False warning: pages with duplicate titles

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/seo-pro#319]
I just upgraded to the latest version and ran a report. Is says:
`250 pages with duplicate titles`, but I've checked and this is not the case.

If you click on each entry the popup says:
`250 pages with "" as the title.`
again, every page has both a title, and a custom meta title.

I've checked both the control panel entries and the front-end pages. Everything seems fine.

**Comment by A5hleyRich** [comment]
I'm also seeing this with any entry that uses a custom Meta Title.

**Comment by jesseleite** [comment]
What versions of statamic/cms and statamic/seo-pro were you on before the upgrade, and which versions are you on now (I assume latest)?

**Comment by A5hleyRich** [comment]
Statamic: 4.56.1
SEO Pro: 5.4.3

I don't know what versions I was on when this worked as expected.

**Comment by jesseleite** [comment]
@stuartcusackie And which version of statamic/cms?

**Comment by jesseleite** [comment]
I'm having a hard time reproducing this 🤔

![CleanShot 2024-04-11 at 10 10 48](https://github.com/statamic/seo-pro/assets/5187394/6ced0b74-73c1-4470-b51c-0f4ef1495229)

And on each entry details...

![CleanShot 2024-04-11 at 10 07 27](https://github.com/statamic/seo-pro/assets/5187394/f7e35025-7eab-48ea-8490-33b6dc2b55f4)

@stuartcusackie And which versions of statamic/cms (Statamic core)?

**Comment by A5hleyRich** [comment]
@jesseleite confirming you're setting a custom meta title:

![CleanShot 2024-04-11 at 15 33 53@2x](https://github.com/statamic/seo-pro/assets/1422996/652f6f93-64c0-4f10-bd33-bc4adac435dc)

**Comment by stuartcusackie** [comment]
@jesseleite It was:
"version": "v4.42.0",
to
"version": "v4.50.0",

And yes, as above, it appears my problem also originates from have custom meta titles.
