### ISSUE TITLE
Collection > Social Image > Custom option missing?

### ISSUE THREAD

**Issue by ryandc** [statamic/seo-pro#327]
As seen here on the marketplace page: https://statamic.com/storage/products/r5ZO6yJSonLMRn0xV4AgyVNmp1hj15ikQ633rRvT.jpeg

I'm using S5, and I see **Inherit** and **From field** as the only options. Has custom been removed?

If so, I'm guessing I have to add a field manually for every collection to allow me to specify a social image? (no big deal, just want clarification)

Thank you

**Comment by jesseleite** [comment]
Hey @ryandc!

No, it has not been removed. You just need to specify a `container` in your seo-pro config...

![CleanShot 2024-05-10 at 11 34 57](https://github.com/statamic/seo-pro/assets/5187394/7abb2e22-9c9d-45ab-b04a-cb4c208873d1)

Once that is set, `Custom` will show 👍

**Comment by jesseleite** [comment]
We've had others ask about this too, so it should be [clearer now in 6.0.1](https://github.com/statamic/seo-pro/releases/tag/6.0.1).
