### ISSUE TITLE
404 sitemap.xml

### ISSUE THREAD

**Issue by jeanfranrene** [statamic/seo-pro#333]
Hi,

Why would I get a 404 error on /sitemap.xml?

I have the file in /resources/views/vendor/seo-pro/sitemap.antlers.html and I also have in config: 
'sitemap' => [
        'enabled' => true,
        'url' => 'sitemap.xml',
        'expire' => 60,
    ],

Thank you!

**Comment by jesseleite** [comment]
Not an issue anymore?

**Comment by jeanfranrene** [comment]
> Not an issue anymore?

No, I deleted /resources/views/vendor/seo-pro/, and tried again php artisan vendor:publish --tag="seo-pro-views" and it worked. thank you!
