### ISSUE TITLE
Error with latest release 6.1.0

### ISSUE THREAD

**Issue by jimblue** [statamic/seo-pro#345]
My website using **SEO-PRO v6.0.3** was perfectly working.
But since I've update to **SEO-PRO v6.1.0** I'm getting the following error:

> Too few arguments to function Statamic\SeoPro\Http\Controllers\SitemapController::show(), 0 passed in /Users/jim/Development/website/vendor/laravel/framework/src/Illuminate/Routing/Controller.php on line 54 and exactly 1 expected

**Comment by duncanmcclean** [comment]
Can you try running `php artisan route:clear`?

**Comment by duncanmcclean** [comment]
Fixed in [6.1.1](https://github.com/statamic/seo-pro/releases/tag/6.1.1).
