### ISSUE TITLE
Showing an update (6.1.1) even when on the latest version (6.1.2)

### ISSUE THREAD

**Issue by aaronbushnell** [statamic/seo-pro#349]
Looks like SEO Pro is showing an update to a version behind the one I'm currently on:

<img width="960" alt="Screenshot 2024-09-12 at 10 53 53 PM" src="https://github.com/user-attachments/assets/0318ca82-0df3-47e3-88c8-9b1b35558f6a">

**Comment by duncanmcclean** [comment]
Thanks, this should be fixed now.
