### ISSUE TITLE
"Translation" missing

### ISSUE THREAD

**Issue by okologi** [statamic/seo-pro#36]
My SEO Pro lacks "translation" several places: cp.settings (left navigation), SEO Pro cp.settings (H1 at settings page), Addons.SeoPro::messages.report Is Being Generated, Addons.SeoPro::messages.back To Reports and so on.

<img width="1052" alt="seo-pro-missing-translation" src="https://user-images.githubusercontent.com/40525614/46250666-f0fe9500-c43f-11e8-89be-e8c630234fc6.png">

Statamic 2.10.5
SEO Pro 1.0.3
Full locale da_DK

**Comment by jasonvarga** [comment]
We don't translate into all languages out of the box.
We only provide English by default.

If you'd like to see how to contribute your language, see how it's done in #38 

As for the `cp.settings` being untranslated, the same thing applies, but for the Statamic translation files. Check for your language here: https://github.com/statamic/i18n
If one doesn't exist, you can create it.

**Comment by okologi** [comment]
I didn’t mean language translation, I just couldn’t find the right word for it.

See attachment.



De bedste hilsner / Best regar
Anders Ørsted-Olsen
Mobil 51 80 25 55
infoDesign
