### ISSUE TITLE
When you update the separator from the control panel

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/seo-pro#37]
If I use a pipe `|` I think the YAML is interpreting it. I have to do `'|'` in order for it to take.

**Comment by jasonvarga** [comment]
Did you type it into a file manually or enter it into the CP?

**Comment by 1stevengrant** [comment]
At first I went through the control panel but updating it to '|' in the yaml file worked.

**Comment by jasonvarga** [comment]
Ah, it's the Spyc YAML parser. You can use the Symfony version which doesn't have this issue, by changing `yaml_parser: symfony` in system.yaml.

Or, just make sure the pipe has quotes around it by hand, like you've done.
