### ISSUE TITLE
Bug while using {{ }} latest version

### ISSUE THREAD

**Issue by kodeine** [statamic/seo-pro#40]
So the title and description fields have {{ company_name }} but the seo plugin is displaying it as empty. But if the same is used anywhere else on the page it works.

**Comment by jasonvarga** [comment]
Where is company_name coming from?

**Comment by vitororlandopinho** [comment]
I have the same problem trying to create a title for my archive page:
```
  /archive/{year}:
    template: blog/archive
    title: 'Archive of {{ year }}'
```
The title on `<head>` is displayed as `Archive of` but the using {{ title }} variable generates `Archive of 2018`

**Comment by jackmcdade** [comment]
Closed due to inactivity. Feel free to reopen with more info! 😊
