### ISSUE TITLE
Enable toggle always shows true for collections

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/seo-pro#42]
In section defaults, go into a collection, toggle enable to be off and save.

The toggle for enabled reverts back to on.

However, check the `folder.yaml` for the collocation and you will see `seo: false`.

So the setting is working, it just always shows as enabled in the CP.

FYI, works fine for taxonomies.

**Comment by jasonvarga** [comment]
This is a bug in Statamic, fixed in 2.10.6 that was released a minute ago.
