### ISSUE TITLE
Editing hreflang in meta.html

### ISSUE THREAD

**Issue by sevfurneaux** [statamic/seo-pro#49]
On our site, we need to edit the specific line: `<link rel="alternate" href="{{ url }}" hreflang="{{ locale }}" />`. We also need to have this "outside" of `alternate_locales`.

In meta.html, it is like this:

```
{{ alternate_locales }}
<link rel="alternate" href="{{ url }}" hreflang="{{ locale }}" />
{{ /alternate_locales }}
```
However, we do not want to list the alternate `locale` `hreflang`, we want the current `locale` instead.

I assume we'd have to "monkey patch" meta.html? Or can we somehow override it somewhere else?

**Comment by sevfurneaux** [comment]
Any help would be much appreciated!

**Comment by jackmcdade** [comment]
I'm note sure I understand what you're looking to accomplish. Is it the same thing as #58?

**Comment by jackmcdade** [comment]
I believe 1.2 addresses this. Feel free to reopen if you were looking for something different!
