### ISSUE TITLE
Problem with multi-locale asset URLs

### ISSUE THREAD

**Issue by ZigaStrgar** [statamic/seo-pro#53]
Upon testing and setting up the SEO PRO add-on on our Statamic page I've stumbled upon a bug when you select a custom image field on a collection item for SEO. While it works fine on default language it breaks when you select any other locale supported on the page.

Default link generated using `{{ seo_pro:meta }}` in layouts file:
`https://statamic.test/img/asset/bWFpbi9sanVibGphbmEtYmcuanBn?p=seo&s=70949a94ecdfcc6cebbb392684d02382`

Link generated on the nondefault locale:

`https://statamic.test/en/en/img/asset/bWFpbi9sanVibGphbmEtYmcuanBn?p=seo&s=70949a94ecdfcc6cebbb392684d02382`

The issue is there in double **`/en/en`** in between which doesn't work.

**Comment by jackmcdade** [comment]
This is technically an issue with the `absolute` parameter on the `glide` tag. Will need to fix this on the Statamic side!
