### ISSUE TITLE
Vague error message when generating a report

### ISSUE THREAD

**Issue by joevallender** [statamic/seo-pro#55]
Just trying to run my first report. The UI was hanging so I tried the command line

```bash
php please seo:report:generate
Generating...
[Symfony\Component\Yaml\Exception\ParseException]  
The YAML value does not appear to be valid UTF-8.
```

I imagine this error is something to do with my site and not the plugin, but it's not very specific and I'm not getting any similar errors elsewhere. The site has been in production for months, and I've only just bought this plugin.

Any clues please?

**Comment by joevallender** [comment]
I thought I'd crudely step through the command. 

It runs `Report::create($id)->generate();`

I can echo out the function calls as far as `->setId()` but cannot echo anything even on the first line of `generate()` in fact, I get the YAML error if I call only `Report::create($id)`

I don't see it getting as far as parsing any of my content files...

**Comment by jackmcdade** [comment]
Good catch!
