### ISSUE TITLE
Add hreflang for active locale

### ISSUE THREAD

**Issue by aerni90** [statamic/seo-pro#58]
According to Google, each language page should specify all the different language versions, **including itself**. SEO Pro only generates a link element for each alternate locale.

To fix this, I manually added this to my head:
```
<link rel="alternate" href="{{ permalink }}" hreflang="{{ locale }}" />
```

I tried to change it directly in the `meta.html` of SEO Pro. However `{{ permalink }}` is not a valid tag in the addon.

This might be related to #49

**Comment by jackmcdade** [comment]
Good call.
