### ISSUE TITLE
Paginated Canonical URL is wrong. Google won't index pages

### ISSUE THREAD

**Issue by madsem** [statamic/seo-pro#62]
A paginated results page with `page=2` for example, has no querystring set and therefore Google will ignore other pages except for the canonical.

`rel="prev/next"` is what's missing and should be included.

**Comment by jackmcdade** [comment]
`rel="prev/next"` isn't necessary anymore, but otherwise it's coming in the next update.

<https://twitter.com/googlewmc/status/1108726443251519489>
<https://www.seroundtable.com/google-rel-prev-next-nothing-has-changed-27308.html>
