### ISSUE TITLE
Search Engine Validation

### ISSUE THREAD

**Issue by madsem** [statamic/seo-pro#64]
We are missing settings where you can paste your Google & Bing meta verification codes.
Should be included imho, it makes things easier :)

Something like this:
(Inspiration from Yoast SEO for wp)
![google_search_verification](https://user-images.githubusercontent.com/3166991/54366696-65856300-4671-11e9-86da-30bfd149a383.png)

**Comment by jackmcdade** [comment]
Nice idea. Coming in the next update.
