### ISSUE TITLE
SEO Tab Not Loading / Erasing Data on Production

### ISSUE THREAD

**Issue by andrewcgregory** [statamic/seo-pro#71]
Running into an issue with loading SEO Pro on production site (works fine in local dev). 
I get a `Failed to load resource: the server responded with a status of 404 ()` for `fieldtype.js` in the console. It points to _resources/addons/SeoPro/js/fieldtype.js and I can load this path just fine in the browser.

So I cannot edit/view the SEO tab on any page on the live website. And if I save the page after viewing the SEO tab it erases all of the SEO field data. 

Statamic: 2.11.14
SEO Pro: 1.1.2

**Comment by jasonvarga** [comment]
What kind of server/environment is being used on production?

**Comment by andrewcgregory** [comment]
Ah, yes, forgot to mention. This is a Digital Ocean server setup through Forge.

**Comment by andrewcgregory** [comment]
Ok, looks like it was the nginx configuration after all. I had to change

```
location ~* ^\/(?!index\.php).*\.(?:css|js|ico|woff|woff2|eot|svg|ttf|otf|png|gif|jpe?g|pdf) {
        expires 7d;
    }
```
to
```
location ~* ^\/(?!index.php|_resources).*\.(?:css|js|ico|woff|woff2|eot|svg|ttf|otf|png|gif|jpe?g|pdf) {
        expires 7d;
    }
```

Thanks Jason for the input.
