### ISSUE TITLE
Error installing trial version

### ISSUE THREAD

**Issue by rizkysyazuli** [statamic/seo-pro#78]
I dowloaded the trial version from the addons [marketplace](https://statamic.com/marketplace/addons/seo-pro). But i got this error when i access my dashboard.

```
FatalThrowableError in Application.php line 575:
Class 'Statamic\Addons\statamic-seo-pro-b8145e3\SeoPro\SeoProServiceProvider' not found
```

**Comment by jackmcdade** [comment]
Gotta double check the install instructions :) 

> Unzip and place the SeoPro directory in your site/addons directory.

You gotta move the `/SeoPro/` directory up a level and get rid of `/statamic-seo-pro-b8145e3\`.
