### ISSUE TITLE
Meta Description: Inherit when Social Image set to Custom Issue

### ISSUE THREAD

**Issue by AdamChlan** [statamic/seo-pro#80]
For an entry within a collection, when I set the Social Image to Custom and pick an image, the Meta Description automatically gets set to the site global default, even though I have it set to "Inherit"...which in my Section Defaults, is supposed to pull a Summary field from the entry. If i don't set a Custom Social Image, the Summary field is pulled as expected.

**Comment by AdamChlan** [comment]
Curious if this is the expected behavior. I can close this out if so. Let me know if I can provide any more details to help understand what I am seeing.

**Comment by jackmcdade** [comment]
That doesn't sound like expected behavior. Not at all. I'll see if I can recreate.

**Comment by AdamChlan** [comment]
Unfortunately I'm still seeing this behavior after updating.

1. Create new entry, including my Summary field, and save. This looks great. My Meta Description takes on my Summary field content.
2. Change my Social Image to a custom image, and save. Meta description changes to the site default, instead of my Summary field, which is how my Section Default for that collection has it set up.

**Comment by jackmcdade** [comment]
Huh, it was working fine for me, but I was testing an explicit value instead of an alternate field reference. Will take another look.

**Comment by AdamChlan** [comment]
Another thing I noticed was that "Save and Continue" gives the impression that it's working as expected. But doing a true Save, and then reopening the entry, shows the issue.

**Comment by jackmcdade** [comment]
Thanks for the tip!

**Comment by jasonvarga** [comment]
Can you please show the contents of the following files:
- `site/settings/addons/seo_pro.yaml`
- `site/content/collections/[the collection]/folder.yaml`
- the entry's md file
- the `version` inside `site/addons/SeoPro/meta.yaml`

**Comment by AdamChlan** [comment]
I can definitely do this if needed, but as I was gathering this info, I found something else that may be useful. It seems like the meta data that is output is correct. I get the summary field outputting as needed. But the backend of Statamic is showing the site default description text any time I add in a custom OG Image.

**Comment by jasonvarga** [comment]
Ahhh okay it's just the helper text that's the issue.

**Comment by AdamChlan** [comment]
It appears so

**Comment by jasonvarga** [comment]
Can you grab the latest from the `develop` branch and try it out?

https://github.com/statamic/seo-pro/archive/develop.zip

**Comment by AdamChlan** [comment]
@jasonvarga this looks good on my end. Thank you!
