### ISSUE TITLE
Setting custom title with page number from pagination

### ISSUE THREAD

**Issue by jeffwhitfield** [statamic/seo-pro#83]
This is sort of related to #62 in that when you have a paginated result, Google expects the title of the page to be unique. Tried to add a custom title with something like {{ get:page }} but that doesn't work. Definitely need to be able to parse tags in the custom titles I think. Any other ideas?  :D

**Comment by jesseleite** [comment]
Fixed in the next version of SEO Pro (not tagged yet), which lets you:

![image](https://user-images.githubusercontent.com/5187394/93255083-60720a00-f767-11ea-8181-3be9d3d4182a.png)

Will tag release soon 👍
