### ISSUE TITLE
Widget dashboard needs some CSS love

### ISSUE THREAD

**Issue by sebszocinski** [statamic/seo-pro#84]
![image](https://user-images.githubusercontent.com/5466694/77597681-8a343c00-6f4f-11ea-8c22-e61770fb3aea.png)

For some reason the [widget html](https://github.com/statamic/seo-pro/blob/master/SeoPro/resources/views/widget.blade.php#L8) has a negative margin of 5 `-mt-5` ?

If it's the only widget it looks fine but if you combine with other widgets the negative margin kicks in and breaks things.

**Comment by jesseleite** [comment]
Fixed in current version 👍

![image](https://user-images.githubusercontent.com/5187394/93235824-162f5f80-f74c-11ea-98a2-f50e1ae4eda5.png)
