### ISSUE TITLE
Site map outputs the home page twice

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/seo-pro#85]
See output below from a new install:

![Screenshot_2020-05-26_at_16 36 17](https://user-images.githubusercontent.com/7669885/83001211-546d0b80-a003-11ea-82f2-031ec3ef6a98.png)

Statamic 2.11.20 and SEO Pro 1.3.3

**Comment by RafaelKr** [comment]
I got the same problem. The sitemap lists the homepage 213(!) times.
When I have time I'll try to debug this further.

Currently still on Statamic 2.11.19 and SEO Pro 1.3.2

**Comment by jesseleite** [comment]
Can't reproduce in current version (statamic/seo-pro 2.0.10 for Statamic v3).  If this is still an issue after updating, let us know!
