### ISSUE TITLE
Sub menu not showing in Control panel 

### ISSUE THREAD

**Issue by paulburgess** [statamic/seo-pro#91]
The side menu isn't showing the Reports / Site defaults / etc. sub menu in the control panel.

I can manually navigate to /cp/addons/seo-pro/defaults via URL and the sub menu is there in the HTML, but the menu li isn't getting the 'visible active' class to reveal the menu.

My local version is OK but my live site has this issue.

![image](https://user-images.githubusercontent.com/504753/88268740-d2c7f000-ccca-11ea-846d-ed86ca7217ec.png)

**Comment by jasonvarga** [comment]
What do you have set for the url in your `system.yaml`'s `locales` array? Put the full https url in there and you should be good.

**Comment by paulburgess** [comment]
Ah great, was missing the s off the http(s), that fixed it - thanks!
