### ISSUE TITLE
Component seo_pro_source-fieldtype does not exist.

### ISSUE THREAD

**Issue by jachno** [statamic/seo-pro#94]
I purchased the Addon for V3, and installed by browsing for it in the marketplace from within my control panel.

Install worked fine but on almost every page I got to it says

Component seo_pro_source-fieldtype does not exist.

![image](https://user-images.githubusercontent.com/6525939/88784767-5466c480-d188-11ea-834d-f25395cc8029.png)

I tried a fresh composer install and a NPM Run dev, but the error remained.

**Comment by jesseleite** [comment]
This is a known issue, and should have happened automatically when you installed SeoPro.  Until then, you can just manually publish SeoPro's assets:

```
php artisan vendor:publish --tag="seo-pro"
```

**Comment by jesseleite** [comment]
Closing this; Fix is coming in next cms beta 👍
