### ISSUE TITLE
Humans take over homepage

### ISSUE THREAD

**Issue by mikemartin** [statamic/seo-pro#95]
No it isn't click bait. 

Humans.txt template view seems to replace the homepage. Publishing SEO Pro's vendor view templates seems to be the only workaround atm.

<img width="1143" alt="Screen Shot 2020-07-30 at 11 40 27 pm" src="https://user-images.githubusercontent.com/414211/88929937-24214200-d2be-11ea-84b6-bcf1dcc1b3db.png">

**Comment by jesseleite** [comment]
We just fixed this issue yesterday.  Need to either `vendor:publish` the config, or update Seo Pro!

**Comment by jesseleite** [comment]
Love that click bait headline though 😂
