### ISSUE TITLE
Wangjangle the Reports Table view and edit actions

### ISSUE THREAD

**Issue by mikemartin** [statamic/seo-pro#96]
<img width="967" alt="Screen Shot 2020-07-31 at 11 33 07 am" src="https://user-images.githubusercontent.com/414211/88990737-1f8e7500-d322-11ea-96bf-a305a7925a15.png">

**Comment by jackmcdade** [comment]
I can't recreate this in Firefox, Safari, or Chrome. Any other clues on what's up? Are there crazy long URLs somewhere lower in the list or anything?

**Comment by mikemartin** [comment]
Hey @jackmcdade, yes there are some crazy long urls in the report. Maybe add an overflow-hidden and truncate it? 
<img width="1003" alt="Screen Shot 2020-08-01 at 12 33 46 am" src="https://user-images.githubusercontent.com/414211/89045348-babd3400-d38e-11ea-80bf-f17bc6c748ab.png">
