### ISSUE TITLE
JS error on collection Blueprint page: Cannot find module './seo_pro.svg'

### ISSUE THREAD

**Issue by pryley** [statamic/seo-pro#98]
<img width="498" alt="Screenshot 2020-08-02 at 16 56 12" src="https://user-images.githubusercontent.com/134939/89133394-1bf51c80-d4e1-11ea-8c6e-e22cd2fb3307.png">

**Comment by jesseleite** [comment]
Are you on latest Statamic beta version?

**Comment by pryley** [comment]
Yes, I'm on v3.0.0-beta.42

![image](https://user-images.githubusercontent.com/134939/89311849-21b34500-d63c-11ea-96e1-61b7745db8bb.png)

![image](https://user-images.githubusercontent.com/134939/89312098-76ef5680-d63c-11ea-8017-1255be817c49.png)

![image](https://user-images.githubusercontent.com/134939/89312160-879fcc80-d63c-11ea-839f-b600d3cb7ae7.png)

**Comment by jesseleite** [comment]
Oh of course, that guy!

**Comment by jasonvarga** [comment]
Fixed in 2.0.6, but it requires statamic/cms beta 45
