### ISSUE TITLE
Browse assets fails from SEO Tab Social Image field

### ISSUE THREAD

**Issue by mikemartin** [statamic/seo-pro#99]
When attempting to upload a Custom SEO image, clicking Browse results in a blank slider.
<img width="1437" alt="Screen Shot 2020-08-08 at 5 09 16 pm" src="https://user-images.githubusercontent.com/414211/89704734-e6957680-d999-11ea-87a9-65dea4b85027.png">

**Comment by jesseleite** [comment]
Fixed in 2.0.5 (will tag soon).
